[features]
seeds = false
skip-lint = false

[programs.devnet]
rust-solana-nft-challenge = "HnMfYirf628dbqboAqWRUsWG6tyF7ACURRyb6irV2osG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/danielgeek/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
